-- EcomTalent admin backend — RUNTIME HEALTH VERIFICATION PACK
-- Generated by the v75 full-sweep audit (2026-06-11). Paste sections into the Supabase SQL editor.
-- Each query carries an EXPECTED / red-flag note. Run top to bottom; start with crons + snapshot freshness.

-- ==========================================================================
-- crons_fired_last_24h_with_cadence
-- Prove all 6 Vercel crons actually fired in the last 24h at the expected cadence, and surface any failures. Cadence per vercel.json (30-day-sprint/vercel.json): 4h routes (check-engagement '0 */4', check-csm-tasks '15 */4', check-na-tasks '20 */4') should show ~6 successful runs; daily routes (sync-whop '0 0', snapshot-progress '30 0', day28-dm '30 9') should show 1. cron_runs schema: route_name, started_at, finished_at, auth_status, status('running'|'success'|'failed'|'auth_failed') from supabase/migrations/2026_v82_cron_runs_audit.sql:22-31; written by src/lib/cron-auth.ts:74-132.
-- EXPECTED: All 6 routes present with verdict OK. 4h routes: successes >= 5 (ideally ~6). Daily routes: successes >= 1. RED-FLAG if any route is missing (Vercel didn't schedule it), has 0 successes, or shows auth_failures > 0 (CRON_SECRET drift — the incident verifyCronAuth was built to catch, src/lib/cron-auth.ts:39-52). still_running > 0 on an old row means a cron crashed mid-run without calling logCronFinish.
-- ==========================================================================
WITH expected(route_name, expected_min_runs, cadence) AS (
  VALUES
    ('sync-whop',         1, 'daily'),
    ('snapshot-progress', 1, 'daily'),
    ('day28-dm',          1, 'daily'),
    ('check-engagement',  5, '4h'),
    ('check-csm-tasks',   5, '4h'),
    ('check-na-tasks',    5, '4h')
),
actual AS (
  SELECT route_name,
         COUNT(*)                                            AS runs_24h,
         COUNT(*) FILTER (WHERE status = 'success')          AS successes,
         COUNT(*) FILTER (WHERE status = 'failed')           AS failures,
         COUNT(*) FILTER (WHERE status = 'auth_failed')      AS auth_failures,
         COUNT(*) FILTER (WHERE status = 'running')          AS still_running,
         MAX(started_at)                                     AS last_started_at,
         MAX(error_message) FILTER (WHERE status IN ('failed','auth_failed')) AS sample_error
  FROM cron_runs
  WHERE started_at >= now() - interval '24 hours'
  GROUP BY route_name
)
SELECT e.route_name,
       e.cadence,
       e.expected_min_runs,
       COALESCE(a.runs_24h, 0)        AS runs_24h,
       COALESCE(a.successes, 0)       AS successes,
       COALESCE(a.failures, 0)        AS failures,
       COALESCE(a.auth_failures, 0)   AS auth_failures,
       COALESCE(a.still_running, 0)   AS still_running,
       a.last_started_at,
       a.sample_error,
       CASE
         WHEN a.route_name IS NULL THEN 'RED-FLAG: route never fired in 24h'
         WHEN COALESCE(a.successes,0) = 0 THEN 'RED-FLAG: zero successful runs'
         WHEN COALESCE(a.successes,0) < e.expected_min_runs THEN 'WARN: fewer successes than expected for cadence'
         WHEN COALESCE(a.auth_failures,0) > 0 THEN 'RED-FLAG: CRON_SECRET auth failing'
         ELSE 'OK'
       END AS verdict
FROM expected e
LEFT JOIN actual a USING (route_name)
ORDER BY e.cadence DESC, e.route_name;


-- ==========================================================================
-- latest_sync_health
-- Confirm the nightly Whop sync (sync_runs) succeeded last night, moved a sane number of rows, and did NOT double-fire. sync_runs schema: started_at, finished_at, source('cron'|'admin-button'), status('success'|'failed'|'running'), fetched, inserted, updated, skipped, errors, error_message, duration_ms from supabase/migrations/2026_v77_cohort_snapshots_and_audit.sql:72-85; written by src/lib/whop-sync-runner.ts:484. The sync feeds first_paid_at/whop_plan_id/canceled_at — if it silently failed, every cohort number downstream is stale.
-- EXPECTED: verdict OK: exactly 1 cron sync in the last 24h, latest_status='success', latest_errors=0, latest_fetched roughly equal to your total Whop community size, latest_finished_at populated. RED-FLAG if 0 cron syncs (the snapshot cron 30 min later then produced stale numbers), >1 cron sync (double-fire), or status<>'success'. A latest row still 'running' with an old started_at means the sync crashed before writing its final sync_runs row.
-- ==========================================================================
WITH recent AS (
  SELECT *
  FROM sync_runs
  WHERE started_at >= now() - interval '36 hours'
  ORDER BY started_at DESC
)
SELECT
  (SELECT COUNT(*) FROM recent WHERE source = 'cron')                            AS cron_runs_36h,
  (SELECT COUNT(*) FROM recent WHERE source = 'cron'
      AND started_at >= now() - interval '24 hours')                              AS cron_runs_24h,
  (SELECT status        FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_status,
  (SELECT source        FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_source,
  (SELECT started_at    FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_started_at,
  (SELECT finished_at   FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_finished_at,
  (SELECT fetched       FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_fetched,
  (SELECT updated       FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_updated,
  (SELECT inserted      FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_inserted,
  (SELECT errors        FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_errors,
  (SELECT error_message FROM recent ORDER BY started_at DESC LIMIT 1)            AS latest_error_message,
  (SELECT duration_ms   FROM recent ORDER BY started_at DESC LIMIT 1)           AS latest_duration_ms,
  CASE
    WHEN (SELECT COUNT(*) FROM recent WHERE source='cron' AND started_at >= now() - interval '24 hours') = 0
      THEN 'RED-FLAG: no cron sync in last 24h'
    WHEN (SELECT COUNT(*) FROM recent WHERE source='cron' AND started_at >= now() - interval '24 hours') > 1
      THEN 'WARN: cron sync double-fired in 24h (only one scheduled at 02:00 UTC)'
    WHEN (SELECT status FROM recent ORDER BY started_at DESC LIMIT 1) <> 'success'
      THEN 'RED-FLAG: latest sync did not succeed'
    WHEN (SELECT errors FROM recent ORDER BY started_at DESC LIMIT 1) > 0
      THEN 'WARN: latest sync reported row-level errors'
    ELSE 'OK'
  END AS verdict;


-- ==========================================================================
-- cohort_integrity_null_first_paid_at
-- INVARIANT 1 + 5: active/past_due paying-plan students with NULL first_paid_at. These are silently OUT of every cohort surface (isInLaunchCohort returns false on NULL — src/lib/admin/metrics-definitions.ts:108-111, no joined_at fallback) yet they ARE paying customers, so they vanish from the dashboard, M2, and CSM crons. Expect 0 after the v75.53 recovery (whop-sync-runner.ts:369-421) + v75.54 backfill. Any row here is the exact leak that produced '91 NULL rows' on 2026-06-11.
-- EXPECTED: 0 rows / count 0, verdict OK. Any count > 0 is a P1 data-coverage finding: those paying members are excluded from dashboard active count, M2 conversion, and CSM task generation. Drill into them with the next query.
-- ==========================================================================
SELECT
  COUNT(*) AS null_first_paid_active_paying,
  CASE WHEN COUNT(*) = 0 THEN 'OK'
       ELSE 'RED-FLAG: active paying students invisible to every cohort surface; run /api/admin/backfill-first-paid-at'
  END AS verdict
FROM students
WHERE membership_status IN ('active','past_due')
  AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
  AND first_paid_at IS NULL;


-- ==========================================================================
-- cohort_integrity_null_first_paid_at_detail
-- Detail rows for the NULL first_paid_at leak so the owner can see WHO is affected (whop_user_id for cross-product recovery) and how long they've been invisible. Complements the count query above. Only run/inspect if the count query returns > 0.
-- EXPECTED: Empty after backfill. If populated, each row is a paying member missing first_paid_at — feed the whop_user_id list to the backfill route. Students whose joined_at is old have been silently uncounted the longest.
-- ==========================================================================
SELECT id, whop_user_id, email, name, membership_status, whop_plan_id,
       joined_at, first_paid_at, csm_exempt, created_at
FROM students
WHERE membership_status IN ('active','past_due')
  AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
  AND first_paid_at IS NULL
ORDER BY joined_at ASC
LIMIT 200;


-- ==========================================================================
-- canceling_vs_churned_coherence
-- INVARIANT 4: canceled_at (access ENDED, terminal) vs cancel_scheduled_at (intent, still active = 'Canceling'). They must never be conflated. This query (a) counts each population, and (b) flags any row where BOTH are set while membership_status is still active/past_due — an incoherent state, since cancel_scheduled_at should be cleared once canceled_at takes over (per supabase/migrations/2026_v83_cancel_scheduled_at.sql:37-38 and isCanceling in metrics-definitions.ts:126-129).
-- EXPECTED: verdict OK. canceling_still_active_paying = the 'Canceling' early-warning population (these students STILL have access and must still appear in active counts + CSM crons). churned_terminal_paying = real churn. incoherent_terminal_stamp_but_active MUST be 0 (canceled_at on an active member would conflate the two semantics and break every active-count consumer). incoherent_both_set_still_active should be 0; a small nonzero is a P2 cleanup, a nonzero terminal-stamp-but-active is a P1.
-- ==========================================================================
SELECT
  COUNT(*) FILTER (
    WHERE cancel_scheduled_at IS NOT NULL
      AND membership_status IN ('active','past_due')
      AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
  ) AS canceling_still_active_paying,
  COUNT(*) FILTER (
    WHERE canceled_at IS NOT NULL
      AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
  ) AS churned_terminal_paying,
  COUNT(*) FILTER (
    WHERE canceled_at IS NOT NULL
      AND cancel_scheduled_at IS NOT NULL
      AND membership_status IN ('active','past_due')
  ) AS incoherent_both_set_still_active,
  COUNT(*) FILTER (
    WHERE canceled_at IS NOT NULL
      AND membership_status IN ('active','past_due')
  ) AS incoherent_terminal_stamp_but_active,
  CASE
    WHEN COUNT(*) FILTER (WHERE canceled_at IS NOT NULL AND membership_status IN ('active','past_due')) > 0
      THEN 'RED-FLAG: canceled_at set on a still-active member (canceled_at must only stamp on transition INTO terminal status)'
    WHEN COUNT(*) FILTER (WHERE canceled_at IS NOT NULL AND cancel_scheduled_at IS NOT NULL AND membership_status IN ('active','past_due')) > 0
      THEN 'WARN: both churn columns set while active; sync runner should clear cancel_scheduled_at once canceled_at takes over'
    ELSE 'OK'
  END AS verdict
FROM students;


-- ==========================================================================
-- dashboard_active_count_vs_snapshot
-- INVARIANT-driven reconciliation: the dashboard's LIVE 'Active on platform' tile vs the latest daily_progress_snapshots.active_count_cohort. The dashboard computes active = active+past_due AND paying plan AND first_paid_at >= cutoff (src/app/admin/(authenticated)/page.tsx:114-125 + :222 activeStudents=students.filter(isPayingMember)). The snapshot cron writes active_count_cohort with the same definition (snapshot-progress/route.ts:133-148). They must match (allow +/-1 for students who churned in the minutes between the snapshot run and now).
-- EXPECTED: diff within +/-1, verdict OK. The snapshot_date should be today or yesterday. A large diff means either the snapshot cron failed (cross-check with crons_fired query), or a cohort-filter divergence between the dashboard query and the cron (would be a P1).
-- ==========================================================================
WITH live AS (
  SELECT COUNT(*) AS live_active_cohort
  FROM students
  WHERE whop_membership_id IS NOT NULL
    AND membership_status IN ('active','past_due')
    AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
    AND first_paid_at >= timestamptz '2026-05-25 00:00:00+00'
),
snap AS (
  SELECT snapshot_date, active_count_cohort
  FROM daily_progress_snapshots
  WHERE active_count_cohort IS NOT NULL
  ORDER BY snapshot_date DESC
  LIMIT 1
)
SELECT live.live_active_cohort,
       snap.active_count_cohort AS snapshot_active_cohort,
       snap.snapshot_date       AS snapshot_date,
       (live.live_active_cohort - snap.active_count_cohort) AS diff,
       CASE
         WHEN snap.active_count_cohort IS NULL THEN 'RED-FLAG: no cohort snapshot exists'
         WHEN abs(live.live_active_cohort - snap.active_count_cohort) <= 1 THEN 'OK'
         WHEN abs(live.live_active_cohort - snap.active_count_cohort) <= 3 THEN 'WARN: small drift (recent join/churn since snapshot)'
         ELSE 'RED-FLAG: dashboard vs snapshot disagree (cohort filter divergence or stale snapshot)'
       END AS verdict
FROM live CROSS JOIN snap;


-- ==========================================================================
-- avg_progress_live_vs_snapshot
-- INVARIANT 6: live cohort avg progress (canonical isLessonComplete via student_progress_counts view, l057 excluded) vs latest daily_progress_snapshots.avg_progress_cohort. Formula: Sum(completed_count over cohort) / (cohort_active_count * total_lessons) * 100. The view (supabase/migrations/2026_v81_canonical_progress_alignment.sql:39-59), the snapshot cron (snapshot-progress/route.ts:169-185,329-338), the RPC, and the dashboard (page.tsx:246-256) must all agree. If hitting Refresh changes the number, these formulas diverged.
-- EXPECTED: diff within ~1 point (rounding/timing), verdict OK. A larger gap means the canonical formula diverged across surfaces (the exact 'how is hitting Refresh changing the number' bug v81 fixed). Note: snapshot rounds to 2dp, dashboard rounds to integer — small diff is normal.
-- ==========================================================================
WITH total_lessons AS (
  SELECT COUNT(*)::numeric AS n FROM lessons WHERE id <> 'l057'
),
cohort AS (
  SELECT id
  FROM students
  WHERE membership_status IN ('active','past_due')
    AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
    AND first_paid_at >= timestamptz '2026-05-25 00:00:00+00'
),
sum_completions AS (
  SELECT COALESCE(SUM(spc.completed_count), 0)::numeric AS total
  FROM student_progress_counts spc
  JOIN cohort c ON c.id = spc.student_id
),
live AS (
  SELECT
    (SELECT COUNT(*) FROM cohort)::numeric AS active_cohort,
    (SELECT total FROM sum_completions)    AS completions,
    (SELECT n FROM total_lessons)          AS total_lessons
),
live_avg AS (
  SELECT CASE WHEN active_cohort > 0 AND total_lessons > 0
              THEN round((completions / (active_cohort * total_lessons)) * 100, 2)
              ELSE 0 END AS live_avg_progress_cohort
  FROM live
),
snap AS (
  SELECT snapshot_date, avg_progress_cohort
  FROM daily_progress_snapshots
  WHERE avg_progress_cohort IS NOT NULL
  ORDER BY snapshot_date DESC
  LIMIT 1
)
SELECT la.live_avg_progress_cohort,
       snap.avg_progress_cohort AS snapshot_avg_progress_cohort,
       snap.snapshot_date,
       round(la.live_avg_progress_cohort - snap.avg_progress_cohort, 2) AS diff,
       CASE
         WHEN snap.avg_progress_cohort IS NULL THEN 'RED-FLAG: no cohort snapshot'
         WHEN abs(la.live_avg_progress_cohort - snap.avg_progress_cohort) <= 1.0 THEN 'OK'
         ELSE 'RED-FLAG: live avg diverges from snapshot (formula drift between view/cron/RPC/dashboard)'
       END AS verdict
FROM live_avg la CROSS JOIN snap;


-- ==========================================================================
-- m2_conversion_numerator_denominator
-- INVARIANT 7: Month-2 conversion sanity, launch-cohort gated, mirroring isMonth2Converted + isInMonth2Cohort (src/lib/admin/metrics-definitions.ts:158-213). Denominator = launch-cohort paying students who reached day 30 (first_paid_at + 30d <= now). Numerator = those, excluding anyone who scheduled cancellation on/before day 30 OR whose canceled_at is on/before day 30. As of 2026-06-11 the earliest cohort student hits day 30 on 2026-06-24, so BOTH should be 0 (metric reads 0/0 = '—').
-- EXPECTED: Before 2026-06-24: m2_denominator = 0 and m2_numerator = 0 (dashboard shows '—'). After that: numerator <= denominator always (verdict RED-FLAG if numerator > denominator). If denominator > 0 well before 2026-06-24, a non-cohort or non-paying student leaked into the M2 pool — check cohort filter.
-- ==========================================================================
WITH cohort AS (
  SELECT *,
         (first_paid_at + interval '30 days') AS day30
  FROM students
  WHERE first_paid_at IS NOT NULL
    AND first_paid_at >= timestamptz '2026-05-25 00:00:00+00'
    AND whop_plan_id IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
),
den AS (
  SELECT * FROM cohort WHERE day30 <= now()
)
SELECT
  (SELECT COUNT(*) FROM den) AS m2_denominator,
  (SELECT COUNT(*) FROM den d
    WHERE NOT (d.cancel_scheduled_at IS NOT NULL AND d.cancel_scheduled_at <= d.day30)
      AND (d.canceled_at IS NULL OR d.canceled_at > d.day30)
  ) AS m2_numerator,
  CASE
    WHEN (SELECT COUNT(*) FROM den) = 0 THEN 'OK: no cohort student has reached day 30 yet (expected before 2026-06-24)'
    WHEN (SELECT COUNT(*) FROM den d
            WHERE NOT (d.cancel_scheduled_at IS NOT NULL AND d.cancel_scheduled_at <= d.day30)
              AND (d.canceled_at IS NULL OR d.canceled_at > d.day30)
         ) > (SELECT COUNT(*) FROM den)
      THEN 'RED-FLAG: numerator exceeds denominator (logic error)'
    ELSE 'OK: numerator <= denominator'
  END AS verdict;


-- ==========================================================================
-- task_queue_health_and_negative_cap
-- INVARIANT 2/3-adjacent + task cap: overall task counts by status, plus the one-open-negative-task-per-student cap. Negative buckets = 'cancel_path' + 'at_risk' (src/lib/csm-triggers.ts SCENARIO_BUCKET:857-880; cron cap logic check-csm-tasks/route.ts:454-549). A student with >1 OPEN negative task is a cap violation. Bucket resolved via templates.bucket join (templates.scenario_id -> tasks.scenario_id).
-- EXPECTED: students_over_negative_cap = 0, verdict OK. open_total should be a small two-digit number for a launch cohort (the code comments cite ~54 open tasks). completed/dismissed grow over time. Any student over the negative cap is a P1 — the supersession logic (sections 3/3b in the cron) failed to dismiss a superseded task.
-- ==========================================================================
WITH task_bucket AS (
  SELECT t.id, t.student_id, t.scenario_id, t.status,
         COALESCE(tmpl.bucket,
                  CASE
                    WHEN t.scenario_id LIKE 'stalled.%' THEN 'cancel_path'
                    WHEN t.scenario_id LIKE 'nolessons.%'
                      OR t.scenario_id LIKE 'noship.%'
                      OR t.scenario_id LIKE 'pace.%' THEN 'at_risk'
                    ELSE 'event'
                  END) AS bucket
  FROM tasks t
  LEFT JOIN templates tmpl ON tmpl.scenario_id = t.scenario_id
),
counts AS (
  SELECT
    COUNT(*) FILTER (WHERE status = 'open')      AS open_total,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed_total,
    COUNT(*) FILTER (WHERE status = 'dismissed') AS dismissed_total
  FROM tasks
),
neg_violations AS (
  SELECT student_id, COUNT(*) AS open_negative
  FROM task_bucket
  WHERE status = 'open' AND bucket IN ('cancel_path','at_risk')
  GROUP BY student_id
  HAVING COUNT(*) > 1
)
SELECT c.open_total, c.completed_total, c.dismissed_total,
       (SELECT COUNT(*) FROM neg_violations) AS students_over_negative_cap,
       (SELECT COALESCE(SUM(open_negative),0) FROM neg_violations) AS total_extra_negative_tasks,
       CASE
         WHEN (SELECT COUNT(*) FROM neg_violations) > 0
           THEN 'RED-FLAG: students hold >1 open negative task (cap in check-csm-tasks should keep this at 0)'
         ELSE 'OK'
       END AS verdict
FROM counts c;


-- ==========================================================================
-- orphan_open_tasks_out_of_cohort
-- INVARIANT 1: open tasks for students who are NOT in the eligible CSM pool (csm_exempt, NULL/non-paying plan, NULL first_paid_at, or first_paid_at before launch cutoff, or not active). The cron's section 3c auto-dismiss (check-csm-tasks/route.ts:628-738) should sweep these. Any open task here means a task is showing in /admin/tasks for someone who should be invisible.
-- EXPECTED: 0, verdict OK. Note: the CSM cron uses TASKS_STUDENT_JOIN_CUTOFF=2026-05-28 (not the 05-25 admin cutoff) plus a 30-day sprint window, so a handful of edge tasks just past those bounds may linger up to a few days before section 3c sweeps them — a small nonzero is a P2/P3, a large or growing number is a P1. Use the detail query to inspect.
-- ==========================================================================
SELECT COUNT(*) AS orphan_open_tasks,
       CASE WHEN COUNT(*) = 0 THEN 'OK'
            ELSE 'WARN: open tasks exist for out-of-cohort/exempt/non-paying students; section 3c auto-dismiss should clear on next run'
       END AS verdict
FROM tasks t
JOIN students s ON s.id = t.student_id
WHERE t.status = 'open'
  AND (
        s.csm_exempt = true
     OR s.membership_status <> 'active'
     OR s.whop_plan_id IS NULL
     OR s.whop_plan_id NOT IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
     OR s.first_paid_at IS NULL
     OR s.first_paid_at < timestamptz '2026-05-25 00:00:00+00'
  );


-- ==========================================================================
-- orphan_open_tasks_detail
-- Detail for orphan open tasks so the owner can see which students/scenarios are stuck. Only inspect if the orphan count query returns > 0.
-- EXPECTED: Empty when the cron is healthy. If populated, each row shows why the student is ineligible (exempt, wrong status, non-paying plan, NULL/pre-launch first_paid_at). Scenario prefix tells you which trigger fired stale.
-- ==========================================================================
SELECT t.id AS task_id, t.scenario_id, t.status, t.created_at,
       s.id AS student_id, s.name, s.membership_status, s.whop_plan_id,
       s.csm_exempt, s.first_paid_at
FROM tasks t
JOIN students s ON s.id = t.student_id
WHERE t.status = 'open'
  AND (
        s.csm_exempt = true
     OR s.membership_status <> 'active'
     OR s.whop_plan_id IS NULL
     OR s.whop_plan_id NOT IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
     OR s.first_paid_at IS NULL
     OR s.first_paid_at < timestamptz '2026-05-25 00:00:00+00'
  )
ORDER BY t.created_at ASC
LIMIT 200;


-- ==========================================================================
-- discount_integrity_null_first_paid
-- INVARIANT 1 + discount integrity: any APPROVED discount belonging to a student with NULL first_paid_at (or otherwise out of cohort). Discount eligibility is gated on first_paid_at (the 15-day window from original signup, constants.ts:104). An approved discount for a NULL-first_paid_at student means the eligibility check ran against missing data. discount_requests schema from supabase/schema.sql:67-77; status set 'approved' in src/app/api/discounts/approve/route.ts:210-214.
-- EXPECTED: approved_with_null_first_paid = 0, verdict OK. approved_pre_launch_cohort may be > 0 for legitimate legacy customers who got discounts pre-launch (informational, not necessarily a bug). Any approved discount tied to a NULL first_paid_at student is a P1 integrity issue.
-- ==========================================================================
SELECT
  COUNT(*) FILTER (WHERE s.first_paid_at IS NULL)                                              AS approved_with_null_first_paid,
  COUNT(*) FILTER (WHERE s.first_paid_at IS NOT NULL
                     AND s.first_paid_at < timestamptz '2026-05-25 00:00:00+00')               AS approved_pre_launch_cohort,
  COUNT(*)                                                                                     AS approved_total,
  CASE
    WHEN COUNT(*) FILTER (WHERE s.first_paid_at IS NULL) > 0
      THEN 'RED-FLAG: approved discount for a student with NULL first_paid_at (eligibility ran against missing data)'
    ELSE 'OK'
  END AS verdict
FROM discount_requests dr
JOIN students s ON s.id = dr.student_id
WHERE dr.status = 'approved';


-- ==========================================================================
-- unknown_paying_plans
-- INVARIANT 1 allowlist drift: active members on a whop_plan_id that is NOT in the allowlist ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75', src/lib/constants.ts:21-24). If a NEW paid plan was created in Whop but not added to PAYING_WHOP_PLAN_IDS (and the matching SQL arrays in the v79/v80/v81 RPC), those members are silently excluded from EVERY operational surface — dashboard, M2, CSM crons, discounts. The sync runner logs a warning per unknown plan; this query surfaces it from the DB directly.
-- EXPECTED: Only known FREE/promo/partner plan ids here (those are intentionally non-paying and excluded by design). RED-FLAG if you see a plan id that should be a PAID plan with a meaningful member count and a recent latest_join — that means a new paid plan launched in Whop and was never added to PAYING_WHOP_PLAN_IDS + the SQL arrays, so its members are invisible to admin. Cross-check any unfamiliar plan id against Whop's plan list.
-- ==========================================================================
SELECT whop_plan_id,
       COUNT(*) AS active_members_on_unknown_plan,
       MIN(joined_at) AS earliest_join,
       MAX(joined_at) AS latest_join
FROM students
WHERE membership_status IN ('active','past_due')
  AND whop_plan_id IS NOT NULL
  AND whop_plan_id NOT IN ('plan_4ZrwR4PmBsVsx','plan_fMMqxAljrzu75')
GROUP BY whop_plan_id
ORDER BY active_members_on_unknown_plan DESC;


-- ==========================================================================
-- snapshot_freshness_and_completeness
-- Supporting check for the snapshot-based reconciliation queries: confirm daily_progress_snapshots has a row for today AND yesterday (the snapshot cron writes both per run, snapshot-progress/route.ts:258-291) and that the cohort columns are populated (not NULL pre-v77 rows). A stale or missing snapshot makes the active_count and avg_progress reconciliation queries meaningless, so run this first.
-- EXPECTED: Two rows (today + yesterday), both with row_exists=true and non-NULL active_count_cohort / avg_progress_cohort, verdict OK. Missing today's row means the 00:30 UTC snapshot cron didn't run (cross-check crons_fired query). NULL cohort columns mean the cron wrote legacy-only — a regression, since post-v77 every write fills both families.
-- ==========================================================================
WITH expected_days AS (
  SELECT (current_date - offs)::date AS day
  FROM generate_series(0,1) AS offs
)
SELECT ed.day AS expected_date,
       dps.snapshot_date IS NOT NULL                          AS row_exists,
       dps.active_count_cohort,
       dps.avg_progress_cohort,
       dps.joined_count_cohort,
       dps.churned_count_cohort,
       CASE
         WHEN dps.snapshot_date IS NULL THEN 'RED-FLAG: no snapshot row for this date (snapshot cron missed it)'
         WHEN dps.active_count_cohort IS NULL THEN 'RED-FLAG: cohort columns NULL (pre-v77 row or cron wrote legacy-only)'
         ELSE 'OK'
       END AS verdict
FROM expected_days ed
LEFT JOIN daily_progress_snapshots dps ON dps.snapshot_date = ed.day
ORDER BY ed.day DESC;


